### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by liwenjie119** [freenet-actions/delete-old-releases#57]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ncipollo/release-action@v1, freenet-actions/delete-old-releases@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by SebastianGoral-freenet** [comment]
This action has been updated to node20 four months ago.
